### PR TITLE
change Home Example descriptions

### PR DESCRIPTION
**Pull request by jixuan1989**

### CODE REVIEW

**Review by stefaniexin — COMMENTED** [review]
【scenarios1】In high-end manufacturing, there are many devices equipped with sensors which can collect working status data. Meteorological stations, wind turbines, etc. are common high-end devices. These devices, if supports Java or Go (in developing), can run TsFile to store data locally. In this way, TsFile can provide the ability to save data with high throughput, high compression ratio, and millisecond query. In addition, with TsFile-Sync tool, TsFiles can be transmitted to the data center equipped with IoTDB instance instead of re-inserting data one point by one point.

**Comment by stefaniexin** [comment]
【scenarios2】In the scene of factories, there are tens of devices under LAN network. IoTDB can be installed on a local controller server in the factory to receive data from those devices. The local controller server (normal PC or workstation) with IoTDB can provide the ability to persist data and query data with SQL-like interface. In addition, with TsFile-Sync tool, TsFiles on the local controller can be transmitted to the data center equipped with IoTDB instance in the cloud.

**Comment by stefaniexin** [comment]
【scenarios3】In the scene of high-speed network (Internet of Vehicles, etc.), a car installed sensors on it can collect monitoring information(driving status, etc.) of itself at a certain frequency. Usually, these automotive devices have limited hardware configurations and are difficult to carry complex applications. Lightweight IoTDB(IoTDB Client) came into being. With JDBC API, it can make data sent by narrow-band IoT or 4G possible. In this way, devices and cloud are connected together.

**Comment by jixuan1989** [comment]
update figs:

iotdb-cloud
iotdb-local
iotdb-machine

**Comment by jixuan1989** [comment]
@stefaniexin  preview:
image

image

image

**Pull request merged**
